export const users = [
    { "name": "Ana", "lastName": "Gómez", "email": "ana.gomez@mail.com", "password": "pass123", "licenseNumber": 101, "specialty_id": 1, "role_id": 2 },
    { "name": "Juan", "lastName": "Pérez", "email": "juan.perez@mail.com", "password": "pass123", "licenseNumber": 102, "specialty_id": 1, "role_id": 2 },
    { "name": "María", "lastName": "López", "email": "maria.lopez@mail.com", "password": "pass123", "licenseNumber": 103, "specialty_id": 1, "role_id": 2 },
    { "name": "Luis", "lastName": "Martínez", "email": "luis.martinez@mail.com", "password": "pass123", "licenseNumber": 104, "specialty_id": 1, "role_id": 2 },
    { "name": "Clara", "lastName": "Fernández", "email": "clara.fernandez@mail.com", "password": "pass123", "licenseNumber": 105, "specialty_id": 1, "role_id": 2 },

    { "name": "Diego", "lastName": "Santos", "email": "diego.santos@mail.com", "password": "pass123", "licenseNumber": 201, "specialty_id": 2, "role_id": 2 },
    { "name": "Elena", "lastName": "Ruiz", "email": "elena.ruiz@mail.com", "password": "pass123", "licenseNumber": 202, "specialty_id": 2, "role_id": 2 },
    { "name": "Oscar", "lastName": "Castro", "email": "oscar.castro@mail.com", "password": "pass123", "licenseNumber": 203, "specialty_id": 2, "role_id": 2 },
    { "name": "Lucía", "lastName": "Morales", "email": "lucia.morales@mail.com", "password": "pass123", "licenseNumber": 204, "specialty_id": 2, "role_id": 2 },
    { "name": "Hugo", "lastName": "Ortega", "email": "hugo.ortega@mail.com", "password": "pass123", "licenseNumber": 205, "specialty_id": 2, "role_id": 2 },

    { "name": "Sofía", "lastName": "Vega", "email": "sofia.vega@mail.com", "password": "pass123", "licenseNumber": 301, "specialty_id": 3, "role_id": 2 },
    { "name": "Carlos", "lastName": "Ramírez", "email": "carlos.ramirez@mail.com", "password": "pass123", "licenseNumber": 302, "specialty_id": 3, "role_id": 2 },
    { "name": "Paula", "lastName": "Torres", "email": "paula.torres@mail.com", "password": "pass123", "licenseNumber": 303, "specialty_id": 3, "role_id": 2 },
    { "name": "Andrés", "lastName": "Suárez", "email": "andres.suarez@mail.com", "password": "pass123", "licenseNumber": 304, "specialty_id": 3, "role_id": 2 },
    { "name": "Valeria", "lastName": "Reyes", "email": "valeria.reyes@mail.com", "password": "pass123", "licenseNumber": 305, "specialty_id": 3, "role_id": 2 },

    { "name": "Federico", "lastName": "Jiménez", "email": "federico.jimenez@mail.com", "password": "pass123", "licenseNumber": 401, "specialty_id": 4, "role_id": 2 },
    { "name": "Isabel", "lastName": "Blanco", "email": "isabel.blanco@mail.com", "password": "pass123", "licenseNumber": 402, "specialty_id": 4, "role_id": 2 },
    { "name": "Ramón", "lastName": "Díaz", "email": "ramon.diaz@mail.com", "password": "pass123", "licenseNumber": 403, "specialty_id": 4, "role_id": 2 },
    { "name": "Patricia", "lastName": "García", "email": "patricia.garcia@mail.com", "password": "pass123", "licenseNumber": 404, "specialty_id": 4, "role_id": 2 },
    { "name": "Ricardo", "lastName": "Molina", "email": "ricardo.molina@mail.com", "password": "pass123", "licenseNumber": 405, "specialty_id": 4, "role_id": 2 },

    { "name": "Natalia", "lastName": "Vargas", "email": "natalia.vargas@mail.com", "password": "pass123", "licenseNumber": 501, "specialty_id": 5, "role_id": 2 },
    { "name": "Gabriel", "lastName": "Rojas", "email": "gabriel.rojas@mail.com", "password": "pass123", "licenseNumber": 502, "specialty_id": 5, "role_id": 2 },
    { "name": "Claudio", "lastName": "Paredes", "email": "claudio.paredes@mail.com", "password": "pass123", "licenseNumber": 503, "specialty_id": 5, "role_id": 2 },
    { "name": "Marcela", "lastName": "Alvarez", "email": "marcela.alvarez@mail.com", "password": "pass123", "licenseNumber": 504, "specialty_id": 5, "role_id": 2 },
    { "name": "Esteban", "lastName": "Castillo", "email": "esteban.castillo@mail.com", "password": "pass123", "licenseNumber": 505, "specialty_id": 5, "role_id": 2 },

    { "name": "Marta", "lastName": "Delgado", "email": "marta.delgado@mail.com", "password": "pass123", "licenseNumber": 601, "specialty_id": 6, "role_id": 2 },
    { "name": "Jorge", "lastName": "Peña", "email": "jorge.pena@mail.com", "password": "pass123", "licenseNumber": 602, "specialty_id": 6, "role_id": 2 },
    { "name": "Teresa", "lastName": "Campos", "email": "teresa.campos@mail.com", "password": "pass123", "licenseNumber": 603, "specialty_id": 6, "role_id": 2 },
    { "name": "Andrés", "lastName": "Guzmán", "email": "andres.guzman@mail.com", "password": "pass123", "licenseNumber": 604, "specialty_id": 6, "role_id": 2 },
    { "name": "Rosa", "lastName": "Navarro", "email": "rosa.navarro@mail.com", "password": "pass123", "licenseNumber": 605, "specialty_id": 6, "role_id": 2 },

    { "name": "Héctor", "lastName": "Muñoz", "email": "hector.munoz@mail.com", "password": "pass123", "licenseNumber": 701, "specialty_id": 7, "role_id": 2 },
    { "name": "Beatriz", "lastName": "Serrano", "email": "beatriz.serrano@mail.com", "password": "pass123", "licenseNumber": 702, "specialty_id": 7, "role_id": 2 },
    { "name": "Alberto", "lastName": "Iglesias", "email": "alberto.iglesias@mail.com", "password": "pass123", "licenseNumber": 703, "specialty_id": 7, "role_id": 2 },
    { "name": "Carmen", "lastName": "Flores", "email": "carmen.flores@mail.com", "password": "pass123", "licenseNumber": 704, "specialty_id": 7, "role_id": 2 },
    { "name": "Manuel", "lastName": "Prieto", "email": "manuel.prieto@mail.com", "password": "pass123", "licenseNumber": 705, "specialty_id": 7, "role_id": 2 },

    { "name": "Ana", "lastName": "Ramos", "email": "ana.ramos@mail.com", "password": "pass123", "licenseNumber": 801, "specialty_id": 8, "role_id": 2 },
    { "name": "Pedro", "lastName": "Santos", "email": "pedro.santos@mail.com", "password": "pass123", "licenseNumber": 802, "specialty_id": 8, "role_id": 2 },
    { "name": "Gloria", "lastName": "Cordero", "email": "gloria.cordero@mail.com", "password": "pass123", "licenseNumber": 803, "specialty_id": 8, "role_id": 2 },
    { "name": "Sergio", "lastName": "Lara", "email": "sergio.lara@mail.com", "password": "pass123", "licenseNumber": 804, "specialty_id": 8, "role_id": 2 },
    { "name": "Elisa", "lastName": "Campos", "email": "elisa.campos@mail.com", "password": "pass123", "licenseNumber": 805, "specialty_id": 8, "role_id": 2 },

    { "name": "Tomás", "lastName": "Nieto", "email": "tomas.nieto@mail.com", "password": "pass123", "licenseNumber": 901, "specialty_id": 9, "role_id": 2 },
    { "name": "Pilar", "lastName": "Del Río", "email": "pilar.delrio@mail.com", "password": "pass123", "licenseNumber": 902, "specialty_id": 9, "role_id": 2 },
    { "name": "Francisco", "lastName": "Acosta", "email": "francisco.acosta@mail.com", "password": "pass123", "licenseNumber": 903, "specialty_id": 9, "role_id": 2 },
    { "name": "Julia", "lastName": "Mora", "email": "julia.mora@mail.com", "password": "pass123", "licenseNumber": 904, "specialty_id": 9, "role_id": 2 },
    { "name": "Roberto", "lastName": "Luna", "email": "roberto.luna@mail.com", "password": "pass123", "licenseNumber": 905, "specialty_id": 9, "role_id": 2 },

    { "name": "Lorena", "lastName": "Aguilar", "email": "lorena.aguilar@mail.com", "password": "pass123", "licenseNumber": 1001, "specialty_id": 10, "role_id": 2 },
    { "name": "Iván", "lastName": "Soto", "email": "ivan.soto@mail.com", "password": "pass123", "licenseNumber": 1002, "specialty_id": 10, "role_id": 2 },
    { "name": "Eva", "lastName": "Domínguez", "email": "eva.dominguez@mail.com", "password": "pass123", "licenseNumber": 1003, "specialty_id": 10, "role_id": 2 },
    { "name": "Raúl", "lastName": "Herrero", "email": "raul.herrero@mail.com", "password": "pass123", "licenseNumber": 1004, "specialty_id": 10, "role_id": 2 },
    { "name": "Mónica", "lastName": "Sáenz", "email": "monica.saenz@mail.com", "password": "pass123", "licenseNumber": 1005, "specialty_id": 10, "role_id": 2 },

    { "name": "Admin1", "lastName": "Control", "email": "admin1@mail.com", "password": "admin123", "licenseNumber": null, "specialty_id": null, "role_id": 3 },
    { "name": "Admin2", "lastName": "Control", "email": "admin2@mail.com", "password": "admin123", "licenseNumber": null, "specialty_id": null, "role_id": 3 },
    { "name": "Admin3", "lastName": "Control", "email": "admin3@mail.com", "password": "admin123", "licenseNumber": null, "specialty_id": null, "role_id": 3 },

    { "name": "Laura", "lastName": "Sánchez", "email": "laura.sanchez@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Fernando", "lastName": "Gil", "email": "fernando.gil@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Marcos", "lastName": "Nuñez", "email": "marcos.nunez@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Camila", "lastName": "Herrera", "email": "camila.herrera@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Alejandro", "lastName": "Méndez", "email": "alejandro.mendez@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Patricia", "lastName": "Silva", "email": "patricia.silva@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Sebastián", "lastName": "Cano", "email": "sebastian.cano@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Natalia", "lastName": "Bravo", "email": "natalia.bravo@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Ricardo", "lastName": "Vidal", "email": "ricardo.vidal@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Verónica", "lastName": "Paz", "email": "veronica.paz@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Daniel", "lastName": "Fuentes", "email": "daniel.fuentes@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Gabriela", "lastName": "Cruz", "email": "gabriela.cruz@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Javier", "lastName": "León", "email": "javier.leon@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Silvia", "lastName": "Pérez", "email": "silvia.perez@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Martín", "lastName": "Campos", "email": "martin.campos@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Claudia", "lastName": "Salazar", "email": "claudia.salazar@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Rodrigo", "lastName": "Moreno", "email": "rodrigo.moreno@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Lorena", "lastName": "Vega", "email": "lorena.vega@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Ignacio", "lastName": "Campos", "email": "ignacio.campos@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Camila", "lastName": "Ortiz", "email": "camila.ortiz@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 },
    { "name": "Bruno", "lastName": "Ramos", "email": "bruno.ramos@mail.com", "password": "pass123", "licenseNumber": null, "specialty_id": null, "role_id": 1 }
]
